#!/usr/bin/env bash
# Run from the repository root.
#
# Regenerate the committed examples/data/ fixtures against the shared trajectory
# (examples/data/trajectory.h5). The committed trajectory is shared by every
# invocation below and is never regenerated by this script. Its parameters:
#   - random initial modes, seed 91798, amplitude 0.1
#   - 100000 integration steps at dt = 0.02
#   - sampling stride 23 (stored dt = 0.46)
# Re-integrating with identical parameters on a different machine (or build) can
# diverge from the committed file: chaotic dynamics amplify floating-point
# differences. The committed trajectory ensures reproducibility.
#
# This script produces exactly the following fixtures:
#   - 8 SSA:                  ssa_r{256,512,768,1024,1280,1536,1792,2048}.h5
#   - 6 PHA derivative sweep: pha_r2048_d1_o{0..5}.h5
#   - 6 PHA rescaled twins:   pha_r2048_d1_o{0..5}_rescaled.h5
#   - 16 PHA delay axis:      pha_r2048_d{3,5,...,33}_o0.h5
#   - 7 PHA cross-resolution: pha_r{256,512,768,1024,1280,1536,1792}_d8_o0.h5
#
# N_JOBS can be overridden via the environment; defaults to -1 (all CPUs).

set -euo pipefail

DATA_DIR="examples/data"
TRAJ="${DATA_DIR}/trajectory.h5"
RPO_FILE="data/rpos_selected.npz"
N_JOBS="${N_JOBS:--1}"

ssa_common=(--method ssa --rpo-file "${RPO_FILE}" --trajectory "${TRAJ}"
            --min-duration 7 --threshold-quantile 0.4 --chunk-size 1000
            --n-jobs "${N_JOBS}" --show-progress)
pha_common=(--method pha --rpo-file "${RPO_FILE}" --trajectory "${TRAJ}"
            --min-duration 7 --threshold-quantile 0.4 --chunk-size 2500
            --n-jobs "${N_JOBS}" --show-progress)

# ssa_r2048
uv run ks-detect "${ssa_common[@]}" --resolution 2048 --output "${DATA_DIR}/ssa_r2048.h5"

# pha_r2048_d1_o{0..5}
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 0 --output "${DATA_DIR}/pha_r2048_d1_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 1 --output "${DATA_DIR}/pha_r2048_d1_o1.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 2 --output "${DATA_DIR}/pha_r2048_d1_o2.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 3 --output "${DATA_DIR}/pha_r2048_d1_o3.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 4 --output "${DATA_DIR}/pha_r2048_d1_o4.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 5 --output "${DATA_DIR}/pha_r2048_d1_o5.h5"

# pha_r2048_d1_o{0..5}_rescaled
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 0 --rescale-orders --output "${DATA_DIR}/pha_r2048_d1_o0_rescaled.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 1 --rescale-orders --output "${DATA_DIR}/pha_r2048_d1_o1_rescaled.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 2 --rescale-orders --output "${DATA_DIR}/pha_r2048_d1_o2_rescaled.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 3 --rescale-orders --output "${DATA_DIR}/pha_r2048_d1_o3_rescaled.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 4 --rescale-orders --output "${DATA_DIR}/pha_r2048_d1_o4_rescaled.h5"
uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay 1 --max-derivative-order 5 --rescale-orders --output "${DATA_DIR}/pha_r2048_d1_o5_rescaled.h5"

# pha_r2048_d{3,5,...,33}_o0
for delay in 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33; do
  uv run ks-detect "${pha_common[@]}" --resolution 2048 --delay "${delay}" --max-derivative-order 0 --output "${DATA_DIR}/pha_r2048_d${delay}_o0.h5"
done

# pha_r{256..1792}_d8_o0
uv run ks-detect "${pha_common[@]}" --resolution 256 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r256_d8_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 512 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r512_d8_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 768 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r768_d8_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 1024 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r1024_d8_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 1280 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r1280_d8_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 1536 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r1536_d8_o0.h5"
uv run ks-detect "${pha_common[@]}" --resolution 1792 --delay 8 --max-derivative-order 0 --output "${DATA_DIR}/pha_r1792_d8_o0.h5"

# ssa_r{256..1792}
uv run ks-detect "${ssa_common[@]}" --resolution 256 --output "${DATA_DIR}/ssa_r256.h5"
uv run ks-detect "${ssa_common[@]}" --resolution 512 --output "${DATA_DIR}/ssa_r512.h5"
uv run ks-detect "${ssa_common[@]}" --resolution 768 --output "${DATA_DIR}/ssa_r768.h5"
uv run ks-detect "${ssa_common[@]}" --resolution 1024 --output "${DATA_DIR}/ssa_r1024.h5"
uv run ks-detect "${ssa_common[@]}" --resolution 1280 --output "${DATA_DIR}/ssa_r1280.h5"
uv run ks-detect "${ssa_common[@]}" --resolution 1536 --output "${DATA_DIR}/ssa_r1536.h5"
uv run ks-detect "${ssa_common[@]}" --resolution 1792 --output "${DATA_DIR}/ssa_r1792.h5"

echo "Done. Wrote result files to ${DATA_DIR}."
